# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://gde-codelabs.github.io/"

title = "Tutorials made by ML-GDE"
languageCode = "en-us"
theme = "codelabs"

[params]
  homeTitle = "Learn Machine Learning through a set of tutorials"
  homeDescription = """
This page delivers Tutorials made by Machine Learning GDE([Google Developers Experts](https://developers.google.com/programs/experts/)). We cover broad range
of topics in Machine Learning including services on Google Cloud Platform such as VertexAI, TensorFlow, TensorFlow Extended, TFLite, and more. 
"""
  footer = "<a href=\"https://github.com/gde-codelabs/gde-codelabs.github.io\">Visit the GitHub Repository</a>"
  feedbackLink = "mailto:deep.diver.csp@gmail.com"
  [params.categoryColors]
    mlops = "#1A73E8"
    tfx = "#f58442"
    gcp = "#3884ff"
    jupyter = "#fc4903"
